# Docker configuration backend

providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.localhost`)"
    swarmMode: true

  file:
    filename: "/etc/traefik/traefik-file-provider.yml"

# API and dashboard configuration
api:
  insecure: true

entrypoints:
  web:
    address: ":80"
  https:
    address: ":443"

accessLog:
  filePath: "/access.log"